version: "3.8"

services:

  myapp:
    image: uwinchester/pfa_app  
    container_name: tomcat-devsecops
    ports:
      - "8080"  
    networks:
      - devsecops-net

  bunkerweb:
    image: bunkerity/bunkerweb:1.5.10
    ports:
      - "80:8080"     # Public HTTP
      - "443:8443"    # Public HTTPS (if needed)
    environment:
      - SERVER_NAME=www.example.com
      - USE_REVERSE_PROXY=yes
      - REVERSE_PROXY_URL=/
      - REVERSE_PROXY_HOST=http://myapp:8080/WebApp/
      - USE_CORAZA=yes
      - CORAZA_API=http://bw-coraza:8080
    networks:
      - bw-universe
      - bw-services

  bw-coraza:
    image: bunkerity/bunkerweb-coraza:latest
    networks:
      - bw-universe

networks:
  bw-universe:
    driver: bridge
  bw-services:
    driver: bridge
