services:
  tomcat:
    image: uwinchester/pfa_app  
    container_name: tomcat-devsecops
    ports:
      - "8080"  
    networks:
      - devsecops-net

  nginx:
    image: owasp/modsecurity-crs:4.14.0-nginx-alpine-202505250105
    container_name: nginx-devsecops
    depends_on:
      - tomcat
    volumes:
      - ./default.conf:/etc/nginx/templates/conf.d/default.conf.template
      - ./setup.conf:/etc/nginx/templates/modsecurity.d/setup.conf.template
      - ./modsecurity.conf:/etc/nginx/templates/conf.d/modsecurity.conf.template
    ports:
      - "80:80"  
    networks:
      - devsecops-net

networks:
  devsecops-net:
    driver: bridge